{{- if and .Values.proxy.enabled .Values.proxy.autoscaling.enabled }}
apiVersion: {{ include "sentinel.hpa.apiVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "sentinel.fullname" . }}-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "sentinel.fullname" . }}-proxy
  minReplicas: {{ .Values.proxy.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.proxy.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.proxy.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.proxy.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.proxy.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.proxy.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- with .Values.proxy.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
